<?php

namespace ApiBundle\Repository;
use ApiBundle\Entity\Group;
use ApiBundle\Entity\Session;
use Doctrine\ORM\EntityRepository;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends EntityRepository
{
    /**
     * Check if there already is a session with that name in that group.
     *
     * TODO: This should be handled by the UniqueEntity validator in the Session entity
     *
     * @param $group
     * @param $session
     * @return boolean Whether a session with the same name already exists in the group
     */
    public function sessionNameExistsInGroup(Group $group, Session $session)
    {
        $existingSession = $this->findOneBy([
            'group' => $group,
            'name' => $session->getName(),
        ]);

        return (bool) $existingSession;
    }
}
